### ISSUE TITLE
Error adding mod metadata 

### ISSUE THREAD

**Issue by Niquolas** [DokiDokiModManager/Mod-Manager#128]
Potential race condition?

```
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at AssertByteCountStream.<anonymous> (C:\Users\onlyf\AppData\Local\Programs\doki-doki-mod-manager\resources\app.asar\lib\main\mod\ModInstaller.js:69:67)
    at AssertByteCountStream.emit (events.js:200:13)
    at AssertByteCountStream.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by Niquolas** [comment]
Fixed - invisible characters are the bane of my existence
